# Generated by Django 5.2.8 on 2025-12-13 17:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objective_relational', '0002_add_inheritance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettypeobj',
            name='discount',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('1.0000'))]),
        ),
    ]
