# Generated by Django 5.2.8 on 2025-12-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relational', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
