# Generated by Django 5.0.6 on 2025-12-08 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relational', '0002_alter_discount_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='event_rel',
        ),
        migrations.AlterModelTable(
            name='eventtype',
            table='event_type',
        ),
        migrations.AlterModelTable(
            name='message',
            table='message_rel',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notification_rel',
        ),
        migrations.AlterModelTable(
            name='order',
            table='order_rel',
        ),
        migrations.AlterModelTable(
            name='ordertickets',
            table='order_tickets',
        ),
        migrations.AlterModelTable(
            name='seattype',
            table='seat_type',
        ),
        migrations.AlterModelTable(
            name='status',
            table='status',
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='ticket_rel',
        ),
        migrations.AlterModelTable(
            name='tickettype',
            table='ticket_type',
        ),
    ]
