# Generated by Django 5.0.6 on 2025-12-06 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relational', '0002_alter_discount_code_alter_event_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='relational.eventtype'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='relational.status'),
        ),
    ]
